-- ============================================================
-- DEPRECATED — Este archivo corre vía docker-entrypoint-initdb.d en el
-- PRIMER boot del container, ANTES de que Prisma cree la tabla AuditLog.
-- Por eso el trigger NUNCA se aplicaba (auditoría 2026-05-25: bug crítico
-- de compliance — audit log mutable en producción).
--
-- El trigger correcto + EXCLUDE constraint anti-doble-booking + GIN indexes
-- pg_trgm viven ahora en `infra/sql/post-deploy.sql`, que el `deploy.sh`
-- ejecuta DESPUÉS de `prisma db push`.
--
-- Este archivo se conserva como no-op solo para no romper docker-compose
-- mounts existentes en el VPS.
-- ============================================================
SELECT 'NOTICE: post-deploy SQL moved to infra/sql/post-deploy.sql' AS notice;
